### PR TITLE
json-stable-stringify@~1.0.0

### PR DESCRIPTION
**Pull request by kenany**

### CODE REVIEW

**Comment by dominictarr** [comment]
Please don't make a PR with no description - it makes my job as maintainer much easier if you include a brief description as to why I should make this merge. Since that is a major version it suggests that may be a breaking change, and if this makes something hash differently it would be a breaking change.

**Comment by kenany** [comment]
@dominictarr Sorry. AFAICT `json-stable-stringify@1.0.0` did not introduce any breaking changes; between `0.1.3` and `1.0.0` only a "replacer" parameter feature was added, Tests in this repo passed with the version bump so I took that as meaning that this would not be a breaking change.

**Comment by brettz9** [comment]
Actually, would you be open to a PR to use [json-stable-stringify-without-jsonify](https://github.com/samn/json-stable-stringify) instead (it just adds [two commits](https://github.com/substack/json-stable-stringify/compare/master...samn:master) and now assumes `JSON`)? The problem with `json-stable-stringify` is that it has a dependency on `jsonify` and jsonify doesn't have a license, bringing problems for all the projects using shasum, e.g., browserify, and all projects using that, etc.

**Comment by brettz9** [comment]
Here are all the changes from 0.1.3 to the latest published 1.0.1: https://github.com/substack/json-stable-stringify/compare/9ad5deb9220c0254b2779ff43764f789978e9fdd..4a3ac9cc006a91e64901f8ebe78d23bf9fc9fbd0

**Comment by dominictarr** [comment]
I no longer have publish access to this module, so I can't merge this anyway. You'll have to fork the module to a new name anyway.

**Pull request closed without merging**
